### ISSUE TITLE
How to handle /dev/ttyUSB0 being changed to /dev/ttyUSB1 ?

### ISSUE THREAD

**Issue by kopax** [pajikos/sms-gammu-gateway#11]
I have an issue with my running container, for some reason, and without a restart, my WWAN device switch from `/dev/ttyUSB0` to `/dev/ttyUSB1`,

How can I avoid this to happen? I am running on Debian buster.

**Comment by pajikos** [comment]
Hi, 
try to create udev rule for your tty usb device:
http://vncprado.github.io/udev-rules-for-ttyusb/
e.g.:
`xxx$ cat /etc/udev/rules.d/10-usb-gsm.rules
ACTION=="add", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1406", SYMLINK+="usb-gsm"`
