### ISSUE TITLE
[Feature request] Delete SMS

### ISSUE THREAD

**Issue by M-Gregoire** [pajikos/sms-gammu-gateway#13]
# Feature request

First of all, thank you for sharing your code which works flawlessly for me. However, I did not see any way to delete SMS, either all of them or by specifying a specific id.

Would this be something you might consider ?

I might be able to submit a PR if this is something you are interested in.

Thank you

**Comment by gpailler** [comment]
Hi @M-Gregoire 

It looks like it's perfect timing. I was looking for something similar and I just created PR #15 that adds new API endpoints to read/delete SMS.

**Comment by M-Gregoire** [comment]
Awesome ! Thanks a lot for your work
