### ISSUE TITLE
[request ]Send a SMS with GET METHOD

### ISSUE THREAD

**Issue by michal-ambroziak** [pajikos/sms-gammu-gateway#19]
Hello,

Would it be possible to implement GET method for sending a SMSes?

for example http://localhost:5000/sms?number=+4740000000&text=SMS message

**Comment by pajikos** [comment]
Hello,
sending SMS is a state change operation (i.e. it is not idempotent), so the POST should be used here: [IDEMPOTENT RESTFUL API](https://restfulapi.net/idempotent-rest-apis/)
You can make a fork and change it there.
Regards
