### ISSUE TITLE
[Question] Is diacritics supported ? 

### ISSUE THREAD

**Issue by rchovan** [pajikos/sms-gammu-gateway#4]
Hi, 
nice work, I want to add it to HomeAssistant. Currently I'm using my Huawei USB modem on Mikrotik router for receiving SMSs, but it does not support diacritics. Is diacritics supported in this local gateway ?

Thanks.

**Comment by rchovan** [comment]
Hi, 
I did some tests, 

- diacritics in gammu is supported with UTF8 encoding
```
Umiestnenie 100001, zložka "Prijaté", pamäť telefónu, Doručené správy
SMS správa
SMSC číslo         : "+421903333000"
Odoslané            : Pi  4. september 2020, 22:08:30 +0200
Kódovanie           : Unicode (bez kompresie)
Vzdialené čísla   : "+421903xxxxxx"
Stav                 : Prečítané

+ľščťžýáíé=oó
```
- diacritics in sms-gammu-gateway is partially supported, characters with diacritics are converted to native characters, like 
š > s, ľ > l , č > c, etc. 

RAW data in HomeAssistant sensor:
![image](https://user-images.githubusercontent.com/6713920/92526196-5d39c400-f225-11ea-8be2-3dc7d00584bc.png)

Parsed message in HomeAssistant
![image](https://user-images.githubusercontent.com/6713920/92525730-a5a4b200-f224-11ea-8626-4b4e41655718.png)

Strange thing, é is not converted to e  😃 

It is better than in Mikrotik, but could you please implement diacritics support ? 
I don't know python, but If you need any other help, I'm free to help.

**Comment by gpailler** [comment]
Hi @rchovan 
I just created the PR #15 with some improvements in message handling. It should fix your issue with diacritics
![image](https://user-images.githubusercontent.com/3621529/108227936-5a9aad80-7179-11eb-9fcb-fe5bffdbbf29.png)
